export const featuredJobs = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120k - $160k",
    posted: "2 days ago",
    description: "We're looking for an experienced frontend developer to join our growing team...",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    featured: true,
  },
  {
    id: "2",
    title: "Product Manager",
    company: "StartupXYZ",
    location: "Remote",
    type: "Full-time",
    salary: "$100k - $140k",
    posted: "1 day ago",
    description: "Lead product strategy and work with cross-functional teams...",
    skills: ["Product Strategy", "Analytics", "Agile", "Leadership"],
    featured: true,
  },
  {
    id: "3",
    title: "UX Designer",
    company: "Design Studio",
    location: "New York, NY",
    type: "Contract",
    salary: "$80k - $100k",
    posted: "3 days ago",
    description: "Create beautiful and intuitive user experiences for our clients...",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
    featured: true,
  },
]